# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci-build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'scripts/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM build/test
      run: |
        npm ci --ignore-scripts
        npm test

    - name: Prepare for Releasing to 'dist'
      run: |
        npm run prepare
        cp -R docs ./lib
        cp README.md ./lib
        cp scripts/release.sh .

    - name: Switch to 'dist' branch
      uses: actions/checkout@v2
      with:
        ref: dist
        clean: false

    - name: Push the transpiling-output code to dist branch
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          bash ./release.sh
